name: md-table
on: [push]
jobs:
  md-lint:
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Dependencies isntall
        run: uv sync
      - name: Run script
        run: uv run table-conv.py
      - name: Save to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "_auto: convert table to makdown"
          git push
